### ISSUE TITLE
No Participant-Level Exclusions Based on Trial-Level Rejections

### ISSUE THREAD

**Issue by palday** [francescomantegna/mlm_music#5]
Verify that even participants with large number of trial-level rejections are in the dataset. I've been harping about this for a while now, but [Ben Bolker said it succinctly recently](https://hypatia.math.ethz.ch/pipermail/r-sig-mixed-models/2020q2/028771.html):

>    This is a very superficial comment that doesn't really engage with  the details of your struggle, but in general it makes me sad when people drop observations, especially from mixed models, and especially in a Bayesian context.  In principle (I know it doesn't always work out this way in practice), observations that are only weakly informative are still giving you *some* information ... is there any way you can solve the problem by setting stronger (i.e. more strongly regularizing) priors ?

@francescomantegna Can you verify that this is the case?

**Comment by francescomantegna** [comment]
Yes, we did not exclude any participant because of large trial-level rejections.

**Comment by palday** [comment]
Excellent.
